# @package _global_

dataset:
  _target_: data.datasets.vor
  width: 64
  height: 64
  num_background_objects: 4
  max_num_objects: 3
  name: vor
  input_channels: 3
  dataset_path: vor.hdf5
  video_dataset: true
  downstream_features: []

# Total available samples: 1_000_000
data_sizes:
  - 10000
  - 1000
  - 1000

